#ifndef Config_hpp
#define Config_hpp

#define CONFIG_ENABLE_TRANSMITTER 0
#define CONFIG_CO2_SENSOR_USE_SOFTWARE_SERIAL 0
//#define CONFIG_CO2_SENSOR_USE_SOFTWARE_SERIAL !CONFIG_ENABLE_TRANSMITTER

#endif
